#this function takes in XML file generated by xmlParse()
#specifically on MeSH Vocabulary file (e.g. desc2015.xml)  years could be varied
#this function extracts DescriptorName,SemanticTypeName and store them into a data frame

ExtractDict <- function(XMLdata){
  
  records <- getNodeSet(XMLdata, "//DescriptorRecord")
  
  #DescriptorUI <- lapply(records, xpathSApply, ".//DescriptorUI", xmlValue)
  #DescriptorUI[sapply(DescriptorUI, is.list)] <- NA
  #DescriptorUI <- sapply(DescriptorUI, paste, collapse = "|")
  
  meshHeadings <- lapply(records, xpathSApply, ".//DescriptorName", xmlValue)
  meshHeadings[sapply(meshHeadings, is.list)] <- NA
  meshHeadings <- sapply(meshHeadings, paste, collapse = "|")
  
  SemanticTypeName <- lapply(records, xpathSApply, ".//SemanticTypeName", xmlValue)
  SemanticTypeName[sapply(SemanticTypeName, is.list)] <- NA
  SemanticTypeName <- sapply(SemanticTypeName, paste, collapse = "|")
  
  
  
  DF <- data.frame(meshHeadings, SemanticTypeName, stringsAsFactors = FALSE)
  #create unique ID to unlist variables later
  #DF$ID<-seq.int(nrow(DF))
  #DF <- select(DF, ID, everything())
  return(DF)
}

